sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
services: sqlite3
before_script:
    - composer self-update
script:
    - composer install --prefer-source
    - php -r "copy('.env.example', '.env');"
    - chmod -R 777 tests/build
    - ./vendor/bin/phpunit
